site_name: Surreal.Net
repo_url: https://github.com/ProphetLamb/Surreal.Net
edit_uri: ""

theme:
  name: material

  palette:
    scheme: slate
  
plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - ./stylesheets/extra.css
