name: Build & Test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SurrealDB
        run: |
          mkdir -p ~/.local/bin
          export INSTALL_DIR=~/.local/bin
          curl -sSf https://install.surrealdb.com | sh
          export PATH="$HOME/.local/bin/:$PATH"
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
        shell: bash
      - name: Run Tests
        run: |
          dotnet test --no-build --verbosity normal --logger "trx;LogFileName=$(pwd)/test-results.trx" --collect:"XPlat Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura\" /p:CoverletOutput="$(pwd)/" /p:UseSourceLink=true
        shell: bash
      - name: Test Report
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: unittest-results
          path: test-results.trx
      - name: Test Coverage
        if: success() || failure()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.cobertura.xml
          flags: unittests
          name: Surreal.Net
          fail_ci_if_error: true
          verbose: true
