name: Docs

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      
      - name: Publish
        run: dotnet publish -f:net60 -c release

      - name: Install MkDocs
        run: pip install mkdocs-material
      
      - name: Install XmlDocMd
        run: dotnet tool install --global xmldocmd --version 2.8.0
      
      - name: Copy README file
        run: cat ./README.md > ./docs/index.md
      
      - name: Generate MD files
        run: ./generate_docs.sh
      
      - name: Deploy
        run: mkdocs gh-deploy --force
